Description = "2B的世界NB的活着!"
Keywords =  "Linux,Docker,K8S,Python"
Subtitle = "个人博客，记录点滴!"
AuthorImg = "/img/avatar.png"
AuthorName = "pengshp"
Introduce = "看尽世间繁华"
DateFormat = "2006-01-02"
YearFormat = "2006年"
MonthFormat = "01-02"

[Footer]
#  StorageLink = "https://gohugo.io/"
#  StorageName = "Hugo"
#  ICPLink = "http://beian.miit.gov.cn"
#  ICPNo = "粤ICP备18047355号"

[[Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/pengshp"

[[Socials]]
  Name = "Twitter"
  Icon = "twitter"
  URL = "https://twitter.com/pengshp"

[[Socials]]
  Name = "知乎"
  Icon = "globe"
  URL = "https://www.zhihu.com/people/prince-37"

[[Links]]
  Name = "高明飞博客"
  Permalink = "https://gaomf.cn/"

[[Links]]
  Name = "老高博客"
  Permalink = "https://blog.phpgao.com/"

[[Links]]
  Name = "Linsir's Blog"
  Permalink = "https://linsir.org/"

[[Links]]
  Name = "SpadesQ"
  Permalink = "http://spadesq.me"

[[Links]]
  Name = "LyShark"
  Permalink = "https://www.cnblogs.com/LyShark"